### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [PierreGode/MMM-airquality#3]
It would be nice if you could move the screenshots to the repository. Without this there will be no screenshot in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/).

**Comment by PierreGode** [comment]
moved the screenshots to /img

**Comment by KristjanESPERANTO** [comment]
Nice. Now your module looks fine in the new module list :slightly_smiling_face:
